# coding: utf-8

"""
    Unified Access Gateway REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.v1_config_adminusers_change_password.post import ChangeUserPassword
from openapi_client.paths.v1_config_adminusers.put import CreateAdminUser
from openapi_client.paths.v1_config_adminusers_id.delete import DeleteAdminUser
from openapi_client.paths.v1_config_adminusers_privileges_id.get import GetAdminPrivileges
from openapi_client.paths.v1_config_adminusers_id.get import GetAdminUser
from openapi_client.paths.v1_config_adminusers.get import GetAllAdminUsers
from openapi_client.paths.v1_config_adminusers_saml_auth.get import GetSamlAuthConfiguration
from openapi_client.paths.v1_config_adminusers_log_admin_user_action_action.get import LogLoginAction
from openapi_client.paths.v1_config_adminusers.post import UpdateAdminUser
from openapi_client.paths.v1_config_adminusers_saml_auth.put import UpdateSamlAuthConfiguration


class AdminUserSettingsApi(
    ChangeUserPassword,
    CreateAdminUser,
    DeleteAdminUser,
    GetAdminPrivileges,
    GetAdminUser,
    GetAllAdminUsers,
    GetSamlAuthConfiguration,
    LogLoginAction,
    UpdateAdminUser,
    UpdateSamlAuthConfiguration,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
