# coding: utf-8

"""
    Unified Access Gateway REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.v1_config_proxy.post import CreateOutboundProxySettings
from openapi_client.paths.v1_config_proxy_name.delete import DeleteProxySettingsGivenByName
from openapi_client.paths.v1_config_proxy.get import GetAllProxySettings
from openapi_client.paths.v1_config_proxy_name.get import GetOutboundProxySettings
from openapi_client.paths.v1_config_proxy.put import UpdateOutboundProxySettings


class OutboundProxySettingsApi(
    CreateOutboundProxySettings,
    DeleteProxySettingsGivenByName,
    GetAllProxySettings,
    GetOutboundProxySettings,
    UpdateOutboundProxySettings,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
