# coding: utf-8

"""
    Unified Access Gateway REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.v1_config_sp_metadata_name.post import CreateSpMetadata
from openapi_client.paths.v1_config_sp_metadata_name.delete import DeleteSpMetadata
from openapi_client.paths.v1_config_sp_metadata_name.get import GetSpMetadata1
from openapi_client.paths.v1_config_sp_metadata.get import GetSpMetadataList
from openapi_client.paths.v1_config_sp_metadata_name.put import PutSpMetadata
from openapi_client.paths.v1_config_sp_metadata.put import PutSpMetadataList


class ServiceProviderMetadataApi(
    CreateSpMetadata,
    DeleteSpMetadata,
    GetSpMetadata1,
    GetSpMetadataList,
    PutSpMetadata,
    PutSpMetadataList,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
