# coding: utf-8

"""
    Unified Access Gateway REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.v1_config_ws1intelligence.post import CreateWs1IntelligenceSettings
from openapi_client.paths.v1_config_ws1intelligence_name.delete import DeleteWs1IntelligenceSettings
from openapi_client.paths.v1_config_ws1intelligence.get import GetAllWs1IntelligenceSettings
from openapi_client.paths.v1_config_ws1intelligence_name.get import GetWs1IntelligenceSettings
from openapi_client.paths.v1_config_ws1intelligence.put import UpdateWs1IntelligenceSettings


class WorkspaceOneIntelligenceSettingsApi(
    CreateWs1IntelligenceSettings,
    DeleteWs1IntelligenceSettings,
    GetAllWs1IntelligenceSettings,
    GetWs1IntelligenceSettings,
    UpdateWs1IntelligenceSettings,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
