# coding: utf-8

"""
    Unified Access Gateway REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class SpMediaType(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            spName = schemas.StrSchema
            metadataXml = schemas.StrSchema
            assertionLifetime = schemas.Int32Schema
            
            
            class _links(
                schemas.DictSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def additional_properties() -> typing.Type['Link']:
                        return Link
                
                def __getitem__(self, name: typing.Union[str, ]) -> 'Link':
                    # dict_instance[name] accessor
                    return super().__getitem__(name)
                
                def get_item_oapg(self, name: typing.Union[str, ]) -> 'Link':
                    return super().get_item_oapg(name)
            
                def __new__(
                    cls,
                    *_args: typing.Union[dict, frozendict.frozendict, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                    **kwargs: 'Link',
                ) -> '_links':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                        **kwargs,
                    )
            __annotations__ = {
                "spName": spName,
                "metadataXml": metadataXml,
                "assertionLifetime": assertionLifetime,
                "_links": _links,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["spName"]) -> MetaOapg.properties.spName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["metadataXml"]) -> MetaOapg.properties.metadataXml: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["assertionLifetime"]) -> MetaOapg.properties.assertionLifetime: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["_links"]) -> MetaOapg.properties._links: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["spName", "metadataXml", "assertionLifetime", "_links", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["spName"]) -> typing.Union[MetaOapg.properties.spName, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["metadataXml"]) -> typing.Union[MetaOapg.properties.metadataXml, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["assertionLifetime"]) -> typing.Union[MetaOapg.properties.assertionLifetime, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["_links"]) -> typing.Union[MetaOapg.properties._links, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["spName", "metadataXml", "assertionLifetime", "_links", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        spName: typing.Union[MetaOapg.properties.spName, str, schemas.Unset] = schemas.unset,
        metadataXml: typing.Union[MetaOapg.properties.metadataXml, str, schemas.Unset] = schemas.unset,
        assertionLifetime: typing.Union[MetaOapg.properties.assertionLifetime, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        _links: typing.Union[MetaOapg.properties._links, dict, frozendict.frozendict, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'SpMediaType':
        return super().__new__(
            cls,
            *_args,
            spName=spName,
            metadataXml=metadataXml,
            assertionLifetime=assertionLifetime,
            _links=_links,
            _configuration=_configuration,
            **kwargs,
        )

from openapi_client.model.link import Link
