# coding: utf-8

"""
    Unified Access Gateway REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class WorkspaceOneIntelligenceRiskScoreSettings(
    schemas.ComposedSchema,
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        
        class all_of_1(
            schemas.DictSchema
        ):
        
        
            class MetaOapg:
                
                class properties:
                    
                    
                    class allowedStatuses(
                        schemas.ListSchema
                    ):
                    
                    
                        class MetaOapg:
                            
                            
                            class items(
                                schemas.EnumBase,
                                schemas.StrSchema
                            ):
                                
                                @schemas.classproperty
                                def LOW(cls):
                                    return cls("LOW")
                                
                                @schemas.classproperty
                                def MEDIUM(cls):
                                    return cls("MEDIUM")
                                
                                @schemas.classproperty
                                def HIGH(cls):
                                    return cls("HIGH")
                                
                                @schemas.classproperty
                                def OTHERS(cls):
                                    return cls("OTHERS")
                    
                        def __new__(
                            cls,
                            _arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, str, ]], typing.List[typing.Union[MetaOapg.items, str, ]]],
                            _configuration: typing.Optional[schemas.Configuration] = None,
                        ) -> 'allowedStatuses':
                            return super().__new__(
                                cls,
                                _arg,
                                _configuration=_configuration,
                            )
                    
                        def __getitem__(self, i: int) -> MetaOapg.items:
                            return super().__getitem__(i)
                    workspaceOneIntelligenceSettingsName = schemas.StrSchema
                    __annotations__ = {
                        "allowedStatuses": allowedStatuses,
                        "workspaceOneIntelligenceSettingsName": workspaceOneIntelligenceSettingsName,
                    }
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["allowedStatuses"]) -> MetaOapg.properties.allowedStatuses: ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["workspaceOneIntelligenceSettingsName"]) -> MetaOapg.properties.workspaceOneIntelligenceSettingsName: ...
            
            @typing.overload
            def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
            
            def __getitem__(self, name: typing.Union[typing_extensions.Literal["allowedStatuses", "workspaceOneIntelligenceSettingsName", ], str]):
                # dict_instance[name] accessor
                return super().__getitem__(name)
            
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["allowedStatuses"]) -> typing.Union[MetaOapg.properties.allowedStatuses, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["workspaceOneIntelligenceSettingsName"]) -> typing.Union[MetaOapg.properties.workspaceOneIntelligenceSettingsName, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
            
            def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["allowedStatuses", "workspaceOneIntelligenceSettingsName", ], str]):
                return super().get_item_oapg(name)
            
        
            def __new__(
                cls,
                *_args: typing.Union[dict, frozendict.frozendict, ],
                allowedStatuses: typing.Union[MetaOapg.properties.allowedStatuses, list, tuple, schemas.Unset] = schemas.unset,
                workspaceOneIntelligenceSettingsName: typing.Union[MetaOapg.properties.workspaceOneIntelligenceSettingsName, str, schemas.Unset] = schemas.unset,
                _configuration: typing.Optional[schemas.Configuration] = None,
                **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
            ) -> 'all_of_1':
                return super().__new__(
                    cls,
                    *_args,
                    allowedStatuses=allowedStatuses,
                    workspaceOneIntelligenceSettingsName=workspaceOneIntelligenceSettingsName,
                    _configuration=_configuration,
                    **kwargs,
                )
        
        @classmethod
        @functools.lru_cache()
        def all_of(cls):
            # we need this here to make our import statements work
            # we must store _composed_schemas in here so the code is only run
            # when we invoke this method. If we kept this at the class
            # level we would get an error because the class level
            # code would be run when this module is imported, and these composed
            # classes don't exist yet because their module has not finished
            # loading
            return [
                DevicePolicySettings,
                cls.all_of_1,
            ]


    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'WorkspaceOneIntelligenceRiskScoreSettings':
        return super().__new__(
            cls,
            *_args,
            _configuration=_configuration,
            **kwargs,
        )

from openapi_client.model.device_policy_settings import DevicePolicySettings
