# coding: utf-8

"""
    Unified Access Gateway REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.v1_config_authmethod_ocsp.delete import DeleteUploadedOcspCertificate
from openapi_client.paths.v1_config_authmethod.get import GetAllAuthMethodSettings
from openapi_client.paths.v1_config_authmethod_ocsp_file_names.get import GetAllUploadedOcspCertificates
from openapi_client.paths.v1_config_authmethod_name.get import GetAuthMethodSettings
from openapi_client.paths.v1_config_authmethod_certificate_auth.get import GetAuthMethodSettingsCertificateAuth
from openapi_client.paths.v1_config_authmethod_radius_auth.get import GetAuthMethodSettingsRadiusAuth
from openapi_client.paths.v1_config_authmethod_securid_auth.get import GetAuthMethodSettingsSecurIdIdp
from openapi_client.paths.v1_config_authmethod_certificate_auth.put import PutAuthMethodSettingsCertificateAuth
from openapi_client.paths.v1_config_authmethod_radius_auth.put import PutAuthMethodSettingsRadiusAuth
from openapi_client.paths.v1_config_authmethod_securid_auth.put import PutAuthMethodSettingsSecurIdIdp
from openapi_client.paths.v1_config_authmethod_reset_name.put import ResetAuthMethodSettings
from openapi_client.paths.v1_config_authmethod_name.put import UpdateAuthMethodSettings
from openapi_client.paths.v1_config_authmethod_ocsp_certificate.put import UploadOcspCertificate


class AuthMethodSettingsApi(
    DeleteUploadedOcspCertificate,
    GetAllAuthMethodSettings,
    GetAllUploadedOcspCertificates,
    GetAuthMethodSettings,
    GetAuthMethodSettingsCertificateAuth,
    GetAuthMethodSettingsRadiusAuth,
    GetAuthMethodSettingsSecurIdIdp,
    PutAuthMethodSettingsCertificateAuth,
    PutAuthMethodSettingsRadiusAuth,
    PutAuthMethodSettingsSecurIdIdp,
    ResetAuthMethodSettings,
    UpdateAuthMethodSettings,
    UploadOcspCertificate,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
