# coding: utf-8

"""
    Unified Access Gateway REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.v1_config_jwt.post import CreateJwtSettings
from openapi_client.paths.v1_config_jwt_name.delete import DeleteAdminUser1
from openapi_client.paths.v1_config_jwt.get import GetAllJwtSettings
from openapi_client.paths.v1_config_jwt_name.get import GetJwtSettings
from openapi_client.paths.v1_config_jwt.put import UpdateJwtSettings


class JWTSettingsApi(
    CreateJwtSettings,
    DeleteAdminUser1,
    GetAllJwtSettings,
    GetJwtSettings,
    UpdateJwtSettings,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
