# coding: utf-8

"""
    Unified Access Gateway REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.v1_config_kerberos_realm.post import AddKcdRealm
from openapi_client.paths.v1_config_kerberos_realm_realm_name.delete import DeleteRealmSettings
from openapi_client.paths.v1_config_kerberos_keytab.get import GetAllPrincipalNamesConfigured
from openapi_client.paths.v1_config_kerberos_realm.get import GetAllRealmsConfigured
from openapi_client.paths.v1_config_kerberos_keytab_principal_name.get import GetKeyTabSetting
from openapi_client.paths.v1_config_kerberos_realm_realm_name.get import GetRealmSettings
from openapi_client.paths.v1_config_kerberos_realm.put import UpdateKcdRealm
from openapi_client.paths.v1_config_kerberos_keytab.put import UploadKeyTab


class KerberosSettingsApi(
    AddKcdRealm,
    DeleteRealmSettings,
    GetAllPrincipalNamesConfigured,
    GetAllRealmsConfigured,
    GetKeyTabSetting,
    GetRealmSettings,
    UpdateKcdRealm,
    UploadKeyTab,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
