# coding: utf-8

"""
    Unified Access Gateway REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.v1_config_syslog.put import CreateOrUpdateSyslogSettings
from openapi_client.paths.v1_config_syslog_host_name.delete import DeleteSyslogServerSettings
from openapi_client.paths.v1_config_syslog_host_name.get import GetSyslogServerSettings
from openapi_client.paths.v1_config_syslog.get import GetSyslogSettings
from openapi_client.paths.v1_config_syslog_host_name.put import UpdateSyslogServerSettings


class SyslogServerSettingsApi(
    CreateOrUpdateSyslogSettings,
    DeleteSyslogServerSettings,
    GetSyslogServerSettings,
    GetSyslogSettings,
    UpdateSyslogServerSettings,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
