# coding: utf-8

# flake8: noqa

# import all models into this package
# if you have many models here with many references from one model to another this may
# raise a RecursionError
# to avoid this, import only the models that you directly need like:
# from openapi_client.model.pet import Pet
# or import this package, but before doing it, use:
# import sys
# sys.setrecursionlimit(n)

from openapi_client.model.admin_saml_settings import AdminSAMLSettings
from openapi_client.model.admin_user import AdminUser
from openapi_client.model.admin_users_list import AdminUsersList
from openapi_client.model.air_watch_cg_edge_service_settings import AirWatchCGEdgeServiceSettings
from openapi_client.model.air_watch_seg_edge_service_settings import AirWatchSEGEdgeServiceSettings
from openapi_client.model.air_watch_tunnel_proxy_edge_service_settings import AirWatchTunnelProxyEdgeServiceSettings
from openapi_client.model.air_watch_tunnel_server_edge_service_settings import AirWatchTunnelServerEdgeServiceSettings
from openapi_client.model.auth_method_settings import AuthMethodSettings
from openapi_client.model.auth_method_settings_list import AuthMethodSettingsList
from openapi_client.model.certificate_auth_method_settings import CertificateAuthMethodSettings
from openapi_client.model.certificate_chain_and_key_wrapper import CertificateChainAndKeyWrapper
from openapi_client.model.change_password_settings import ChangePasswordSettings
from openapi_client.model.configured_auth_method import ConfiguredAuthMethod
from openapi_client.model.configured_edge_service import ConfiguredEdgeService
from openapi_client.model.configured_edge_services_and_auth_method_list import ConfiguredEdgeServicesAndAuthMethodList
from openapi_client.model.core_dump_settings import CoreDumpSettings
from openapi_client.model.custom_branding import CustomBranding
from openapi_client.model.custom_branding_settings import CustomBrandingSettings
from openapi_client.model.custom_executable_list import CustomExecutableList
from openapi_client.model.device_policy_settings import DevicePolicySettings
from openapi_client.model.device_policy_settings_list import DevicePolicySettingsList
from openapi_client.model.device_status import DeviceStatus
from openapi_client.model.edge_service_settings import EdgeServiceSettings
from openapi_client.model.edge_service_settings_list import EdgeServiceSettingsList
from openapi_client.model.flags import Flags
from openapi_client.model.general_settings import GeneralSettings
from openapi_client.model.hosted_resource_metadata import HostedResourceMetadata
from openapi_client.model.id_p_external_metadata_settings import IdPExternalMetadataSettings
from openapi_client.model.id_p_external_metadata_settings_list import IdPExternalMetadataSettingsList
from openapi_client.model.idp_media_type import IdpMediaType
from openapi_client.model.jwt_issuer_settings import JWTIssuerSettings
from openapi_client.model.jwt_issuer_settings_list import JWTIssuerSettingsList
from openapi_client.model.jwt_settings import JWTSettings
from openapi_client.model.jwt_settings_list import JWTSettingsList
from openapi_client.model.kerberos_key_tab_settings import KerberosKeyTabSettings
from openapi_client.model.kerberos_key_tab_settings_list import KerberosKeyTabSettingsList
from openapi_client.model.kerberos_realm_settings import KerberosRealmSettings
from openapi_client.model.kerberos_realm_settings_list import KerberosRealmSettingsList
from openapi_client.model.link import Link
from openapi_client.model.load_balancer_settings import LoadBalancerSettings
from openapi_client.model.modified_admin_user import ModifiedAdminUser
from openapi_client.model.nic_settings import NicSettings
from openapi_client.model.nic_settings_list import NicSettingsList
from openapi_client.model.ocsp_signing_cert_list import OCSPSigningCertList
from openapi_client.model.opswat_device_policy_settings import OpswatDevicePolicySettings
from openapi_client.model.outbound_proxy_settings import OutboundProxySettings
from openapi_client.model.outbound_proxy_settings_list import OutboundProxySettingsList
from openapi_client.model.package_update_settings import PackageUpdateSettings
from openapi_client.model.password_policy_settings import PasswordPolicySettings
from openapi_client.model.pfx_cert_store_wrapper import PfxCertStoreWrapper
from openapi_client.model.public_key_or_cert import PublicKeyOrCert
from openapi_client.model.radius_auth_method_settings import RadiusAuthMethodSettings
from openapi_client.model.resource_settings import ResourceSettings
from openapi_client.model.secur_id_idp_method_settings import SecurIDIdpMethodSettings
from openapi_client.model.security_agent_settings import SecurityAgentSettings
from openapi_client.model.security_agent_settings_list import SecurityAgentSettingsList
from openapi_client.model.server_settings import ServerSettings
from openapi_client.model.settings import Settings
from openapi_client.model.snmp_settings import SnmpSettings
from openapi_client.model.sp_media_type import SpMediaType
from openapi_client.model.sp_media_types import SpMediaTypes
from openapi_client.model.ssh_public_key import SshPublicKey
from openapi_client.model.syslog_server_settings import SyslogServerSettings
from openapi_client.model.syslog_settings import SyslogSettings
from openapi_client.model.system_settings import SystemSettings
from openapi_client.model.tls_mqtt_server_settings import TlsMqttServerSettings
from openapi_client.model.tls_syslog_server_settings import TlsSyslogServerSettings
from openapi_client.model.uag_feature_flag_info import UAGFeatureFlagInfo
from openapi_client.model.view_edge_service_settings import ViewEdgeServiceSettings
from openapi_client.model.ws1_intelligence_credentials import WS1IntelligenceCredentials
from openapi_client.model.ws1_intelligence_data import WS1IntelligenceData
from openapi_client.model.ws1_intelligence_o_auth_client import WS1IntelligenceOAuthClient
from openapi_client.model.ws1_intelligence_settings_list import WS1IntelligenceSettingsList
from openapi_client.model.wazuh_agent_settings import WazuhAgentSettings
from openapi_client.model.workspace_one_intelligence_data_settings import WorkspaceOneIntelligenceDataSettings
from openapi_client.model.workspace_one_intelligence_risk_score_settings import WorkspaceOneIntelligenceRiskScoreSettings
from openapi_client.model.workspace_one_intelligence_settings import WorkspaceOneIntelligenceSettings
from openapi_client.model.ws_portal_edge_service_settings import WsPortalEdgeServiceSettings
