# coding: utf-8

"""
    Unified Access Gateway REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class DeviceStatus(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            errorMessage = schemas.StrSchema
            statusValue = schemas.StrSchema
            allowed = schemas.BoolSchema
            iniFieldName = schemas.StrSchema
            __annotations__ = {
                "errorMessage": errorMessage,
                "statusValue": statusValue,
                "allowed": allowed,
                "iniFieldName": iniFieldName,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["errorMessage"]) -> MetaOapg.properties.errorMessage: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["statusValue"]) -> MetaOapg.properties.statusValue: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["allowed"]) -> MetaOapg.properties.allowed: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["iniFieldName"]) -> MetaOapg.properties.iniFieldName: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["errorMessage", "statusValue", "allowed", "iniFieldName", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["errorMessage"]) -> typing.Union[MetaOapg.properties.errorMessage, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["statusValue"]) -> typing.Union[MetaOapg.properties.statusValue, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["allowed"]) -> typing.Union[MetaOapg.properties.allowed, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["iniFieldName"]) -> typing.Union[MetaOapg.properties.iniFieldName, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["errorMessage", "statusValue", "allowed", "iniFieldName", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        errorMessage: typing.Union[MetaOapg.properties.errorMessage, str, schemas.Unset] = schemas.unset,
        statusValue: typing.Union[MetaOapg.properties.statusValue, str, schemas.Unset] = schemas.unset,
        allowed: typing.Union[MetaOapg.properties.allowed, bool, schemas.Unset] = schemas.unset,
        iniFieldName: typing.Union[MetaOapg.properties.iniFieldName, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'DeviceStatus':
        return super().__new__(
            cls,
            *_args,
            errorMessage=errorMessage,
            statusValue=statusValue,
            allowed=allowed,
            iniFieldName=iniFieldName,
            _configuration=_configuration,
            **kwargs,
        )
