# coding: utf-8

"""
    Unified Access Gateway REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class PackageUpdateSettings(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            
            
            class packageUpdatesScheme(
                schemas.EnumBase,
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    enum_value_to_name = {
                        "OFF": "OFF",
                        "ON_NEXT_BOOT": "ON_NEXT_BOOT",
                        "ON_EVERY_BOOT": "ON_EVERY_BOOT",
                    }
                
                @schemas.classproperty
                def OFF(cls):
                    return cls("OFF")
                
                @schemas.classproperty
                def ON_NEXT_BOOT(cls):
                    return cls("ON_NEXT_BOOT")
                
                @schemas.classproperty
                def ON_EVERY_BOOT(cls):
                    return cls("ON_EVERY_BOOT")
            packageUpdatesOSURL = schemas.StrSchema
            packageUpdatesURL = schemas.StrSchema
            
            
            class trustedCertificates(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['PublicKeyOrCert']:
                        return PublicKeyOrCert
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple['PublicKeyOrCert'], typing.List['PublicKeyOrCert']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'trustedCertificates':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'PublicKeyOrCert':
                    return super().__getitem__(i)
            __annotations__ = {
                "packageUpdatesScheme": packageUpdatesScheme,
                "packageUpdatesOSURL": packageUpdatesOSURL,
                "packageUpdatesURL": packageUpdatesURL,
                "trustedCertificates": trustedCertificates,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["packageUpdatesScheme"]) -> MetaOapg.properties.packageUpdatesScheme: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["packageUpdatesOSURL"]) -> MetaOapg.properties.packageUpdatesOSURL: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["packageUpdatesURL"]) -> MetaOapg.properties.packageUpdatesURL: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["trustedCertificates"]) -> MetaOapg.properties.trustedCertificates: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["packageUpdatesScheme", "packageUpdatesOSURL", "packageUpdatesURL", "trustedCertificates", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["packageUpdatesScheme"]) -> typing.Union[MetaOapg.properties.packageUpdatesScheme, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["packageUpdatesOSURL"]) -> typing.Union[MetaOapg.properties.packageUpdatesOSURL, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["packageUpdatesURL"]) -> typing.Union[MetaOapg.properties.packageUpdatesURL, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["trustedCertificates"]) -> typing.Union[MetaOapg.properties.trustedCertificates, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["packageUpdatesScheme", "packageUpdatesOSURL", "packageUpdatesURL", "trustedCertificates", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        packageUpdatesScheme: typing.Union[MetaOapg.properties.packageUpdatesScheme, str, schemas.Unset] = schemas.unset,
        packageUpdatesOSURL: typing.Union[MetaOapg.properties.packageUpdatesOSURL, str, schemas.Unset] = schemas.unset,
        packageUpdatesURL: typing.Union[MetaOapg.properties.packageUpdatesURL, str, schemas.Unset] = schemas.unset,
        trustedCertificates: typing.Union[MetaOapg.properties.trustedCertificates, list, tuple, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'PackageUpdateSettings':
        return super().__new__(
            cls,
            *_args,
            packageUpdatesScheme=packageUpdatesScheme,
            packageUpdatesOSURL=packageUpdatesOSURL,
            packageUpdatesURL=packageUpdatesURL,
            trustedCertificates=trustedCertificates,
            _configuration=_configuration,
            **kwargs,
        )

from openapi_client.model.public_key_or_cert import PublicKeyOrCert
