# coding: utf-8

"""
    Unified Access Gateway REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class SecurIDIdpMethodSettings(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "hostname",
            "numIterationsRest",
            "certificateRest",
            "serverPortRest",
            "name",
            "serverHostnameRest",
            "authenticationTimeoutRest",
            "accessKeyRest",
            "enabled",
        }
        
        class properties:
            name = schemas.StrSchema
            enabled = schemas.BoolSchema
            numIterationsRest = schemas.StrSchema
            serverHostnameRest = schemas.StrSchema
            serverPortRest = schemas.StrSchema
            hostname = schemas.StrSchema
            accessKeyRest = schemas.StrSchema
            certificateRest = schemas.StrSchema
            authenticationTimeoutRest = schemas.StrSchema
            className = schemas.StrSchema
            displayName = schemas.StrSchema
            jarFile = schemas.StrSchema
            authMethod = schemas.StrSchema
            versionNum = schemas.StrSchema
            __annotations__ = {
                "name": name,
                "enabled": enabled,
                "numIterationsRest": numIterationsRest,
                "serverHostnameRest": serverHostnameRest,
                "serverPortRest": serverPortRest,
                "hostname": hostname,
                "accessKeyRest": accessKeyRest,
                "certificateRest": certificateRest,
                "authenticationTimeoutRest": authenticationTimeoutRest,
                "className": className,
                "displayName": displayName,
                "jarFile": jarFile,
                "authMethod": authMethod,
                "versionNum": versionNum,
            }
    
    hostname: MetaOapg.properties.hostname
    numIterationsRest: MetaOapg.properties.numIterationsRest
    certificateRest: MetaOapg.properties.certificateRest
    serverPortRest: MetaOapg.properties.serverPortRest
    name: MetaOapg.properties.name
    serverHostnameRest: MetaOapg.properties.serverHostnameRest
    authenticationTimeoutRest: MetaOapg.properties.authenticationTimeoutRest
    accessKeyRest: MetaOapg.properties.accessKeyRest
    enabled: MetaOapg.properties.enabled
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["enabled"]) -> MetaOapg.properties.enabled: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["numIterationsRest"]) -> MetaOapg.properties.numIterationsRest: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["serverHostnameRest"]) -> MetaOapg.properties.serverHostnameRest: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["serverPortRest"]) -> MetaOapg.properties.serverPortRest: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["hostname"]) -> MetaOapg.properties.hostname: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["accessKeyRest"]) -> MetaOapg.properties.accessKeyRest: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["certificateRest"]) -> MetaOapg.properties.certificateRest: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["authenticationTimeoutRest"]) -> MetaOapg.properties.authenticationTimeoutRest: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["className"]) -> MetaOapg.properties.className: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["displayName"]) -> MetaOapg.properties.displayName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["jarFile"]) -> MetaOapg.properties.jarFile: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["authMethod"]) -> MetaOapg.properties.authMethod: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["versionNum"]) -> MetaOapg.properties.versionNum: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["name", "enabled", "numIterationsRest", "serverHostnameRest", "serverPortRest", "hostname", "accessKeyRest", "certificateRest", "authenticationTimeoutRest", "className", "displayName", "jarFile", "authMethod", "versionNum", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["enabled"]) -> MetaOapg.properties.enabled: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["numIterationsRest"]) -> MetaOapg.properties.numIterationsRest: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["serverHostnameRest"]) -> MetaOapg.properties.serverHostnameRest: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["serverPortRest"]) -> MetaOapg.properties.serverPortRest: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["hostname"]) -> MetaOapg.properties.hostname: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["accessKeyRest"]) -> MetaOapg.properties.accessKeyRest: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["certificateRest"]) -> MetaOapg.properties.certificateRest: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["authenticationTimeoutRest"]) -> MetaOapg.properties.authenticationTimeoutRest: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["className"]) -> typing.Union[MetaOapg.properties.className, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["displayName"]) -> typing.Union[MetaOapg.properties.displayName, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["jarFile"]) -> typing.Union[MetaOapg.properties.jarFile, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["authMethod"]) -> typing.Union[MetaOapg.properties.authMethod, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["versionNum"]) -> typing.Union[MetaOapg.properties.versionNum, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["name", "enabled", "numIterationsRest", "serverHostnameRest", "serverPortRest", "hostname", "accessKeyRest", "certificateRest", "authenticationTimeoutRest", "className", "displayName", "jarFile", "authMethod", "versionNum", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        hostname: typing.Union[MetaOapg.properties.hostname, str, ],
        numIterationsRest: typing.Union[MetaOapg.properties.numIterationsRest, str, ],
        certificateRest: typing.Union[MetaOapg.properties.certificateRest, str, ],
        serverPortRest: typing.Union[MetaOapg.properties.serverPortRest, str, ],
        name: typing.Union[MetaOapg.properties.name, str, ],
        serverHostnameRest: typing.Union[MetaOapg.properties.serverHostnameRest, str, ],
        authenticationTimeoutRest: typing.Union[MetaOapg.properties.authenticationTimeoutRest, str, ],
        accessKeyRest: typing.Union[MetaOapg.properties.accessKeyRest, str, ],
        enabled: typing.Union[MetaOapg.properties.enabled, bool, ],
        className: typing.Union[MetaOapg.properties.className, str, schemas.Unset] = schemas.unset,
        displayName: typing.Union[MetaOapg.properties.displayName, str, schemas.Unset] = schemas.unset,
        jarFile: typing.Union[MetaOapg.properties.jarFile, str, schemas.Unset] = schemas.unset,
        authMethod: typing.Union[MetaOapg.properties.authMethod, str, schemas.Unset] = schemas.unset,
        versionNum: typing.Union[MetaOapg.properties.versionNum, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'SecurIDIdpMethodSettings':
        return super().__new__(
            cls,
            *_args,
            hostname=hostname,
            numIterationsRest=numIterationsRest,
            certificateRest=certificateRest,
            serverPortRest=serverPortRest,
            name=name,
            serverHostnameRest=serverHostnameRest,
            authenticationTimeoutRest=authenticationTimeoutRest,
            accessKeyRest=accessKeyRest,
            enabled=enabled,
            className=className,
            displayName=displayName,
            jarFile=jarFile,
            authMethod=authMethod,
            versionNum=versionNum,
            _configuration=_configuration,
            **kwargs,
        )
