# coding: utf-8

"""
    VxRail REST API

    The VxRail REST API provides a programmatic interface for performing VxRail administrative tasks. Data is available in JSON format.  # noqa: E501

    OpenAPI spec version: 8.0.020
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.initialize_diskslotmappings_body import InitializeDiskslotmappingsBody  # noqa: E501
from swagger_client.rest import ApiException


class TestInitializeDiskslotmappingsBody(unittest.TestCase):
    """InitializeDiskslotmappingsBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInitializeDiskslotmappingsBody(self):
        """Test InitializeDiskslotmappingsBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.initialize_diskslotmappings_body.InitializeDiskslotmappingsBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
