# coding: utf-8

"""
    VxRail REST API

    The VxRail REST API provides a programmatic interface for performing VxRail administrative tasks. Data is available in JSON format.  # noqa: E501

    OpenAPI spec version: 8.0.020
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.support_knowledge_base_api import SupportKnowledgeBaseApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSupportKnowledgeBaseApi(unittest.TestCase):
    """SupportKnowledgeBaseApi unit test stubs"""

    def setUp(self):
        self.api = SupportKnowledgeBaseApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1_kb_articels_get(self):
        """Test case for v1_kb_articels_get

        Get articles from the Support Knowledge Base  # noqa: E501
        """
        pass

    def test_v1_kb_get(self):
        """Test case for v1_kb_get

        Get the URL of the Support Knowledge Base  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
