# coding: utf-8

"""
    VxRail REST API

    The VxRail REST API provides a programmatic interface for performing VxRail administrative tasks. Data is available in JSON format.  # noqa: E501

    OpenAPI spec version: 8.0.020
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.support_community_forum_api import SupportCommunityForumApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSupportCommunityForumApi(unittest.TestCase):
    """SupportCommunityForumApi unit test stubs"""

    def setUp(self):
        self.api = SupportCommunityForumApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1_support_community_get(self):
        """Test case for v1_support_community_get

        Get the home URL for accessing the VxRail community  # noqa: E501
        """
        pass

    def test_v1_support_community_message_get(self):
        """Test case for v1_support_community_message_get

        Get VxRail community messages  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
