# coding: utf-8

"""
    VxRail REST API

    The VxRail REST API provides a programmatic interface for performing VxRail administrative tasks. Data is available in JSON format.  # noqa: E501

    OpenAPI spec version: 8.0.020
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.support_chat_api import SupportChatApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSupportChatApi(unittest.TestCase):
    """SupportChatApi unit test stubs"""

    def setUp(self):
        self.api = SupportChatApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1_support_chat_url_get(self):
        """Test case for v1_support_chat_url_get

        Get a URL to start a chat session with a Dell Support  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
