# coding: utf-8

"""
    VxRail REST API

    The VxRail REST API provides a programmatic interface for performing VxRail administrative tasks. Data is available in JSON format.  # noqa: E501

    OpenAPI spec version: 8.0.020
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.cvs_public_api import CVSPublicApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCVSPublicApi(unittest.TestCase):
    """CVSPublicApi unit test stubs"""

    def setUp(self):
        self.api = CVSPublicApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_generate_advisory_report_public(self):
        """Test case for generate_advisory_report_public

        Generate an advisory report of all online and local updates  # noqa: E501
        """
        pass

    def test_generate_compliance_report_public(self):
        """Test case for generate_compliance_report_public

        Generate a compliance drift report  # noqa: E501
        """
        pass

    def test_lcm_advisory_meta_bundle_post(self):
        """Test case for lcm_advisory_meta_bundle_post

        Upload an advisory metadata bundle  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
