# coding: utf-8

"""
    VxRail REST API

    The VxRail REST API provides a programmatic interface for performing VxRail administrative tasks. Data is available in JSON format.  # noqa: E501

    OpenAPI spec version: 8.0.020
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.lcm_pre_check_api import LCMPreCheckApi  # noqa: E501
from swagger_client.rest import ApiException


class TestLCMPreCheckApi(unittest.TestCase):
    """LCMPreCheckApi unit test stubs"""

    def setUp(self):
        self.api = LCMPreCheckApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_precheck_v1(self):
        """Test case for precheck_v1

        Perform a health pre-check  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
