# coding: utf-8

"""
    VxRail REST API

    The VxRail REST API provides a programmatic interface for performing VxRail administrative tasks. Data is available in JSON format.  # noqa: E501

    OpenAPI spec version: 8.0.020
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.disk_information_api import DiskInformationApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDiskInformationApi(unittest.TestCase):
    """DiskInformationApi unit test stubs"""

    def setUp(self):
        self.api = DiskInformationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1_disks_get(self):
        """Test case for v1_disks_get

        Get a list of disks  # noqa: E501
        """
        pass

    def test_v1_disks_sn_get(self):
        """Test case for v1_disks_sn_get

        Get information about a disk  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
