# coding: utf-8

"""
    VxRail REST API

    The VxRail REST API provides a programmatic interface for performing VxRail administrative tasks. Data is available in JSON format.  # noqa: E501

    OpenAPI spec version: 8.0.020
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.request_status_api import RequestStatusApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRequestStatusApi(unittest.TestCase):
    """RequestStatusApi unit test stubs"""

    def setUp(self):
        self.api = RequestStatusApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1_request_id_get(self):
        """Test case for v1_request_id_get

        Get the status of a request  # noqa: E501
        """
        pass

    def test_v1_requests_get(self):
        """Test case for v1_requests_get

        Query all requests  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
