# coding: utf-8

"""
    VxRail REST API

    The VxRail REST API provides a programmatic interface for performing VxRail administrative tasks. Data is available in JSON format.  # noqa: E501

    OpenAPI spec version: 8.0.020
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.call_home_operations_api import CallHomeOperationsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCallHomeOperationsApi(unittest.TestCase):
    """CallHomeOperationsApi unit test stubs"""

    def setUp(self):
        self.api = CallHomeOperationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_callhome_info_get_v1(self):
        """Test case for callhome_info_get_v1

        Get call home server information (v1)  # noqa: E501
        """
        pass

    def test_v1_callhome_access_code_post(self):
        """Test case for v1_callhome_access_code_post

        Generate access code to activate internal call home server  # noqa: E501
        """
        pass

    def test_v1_callhome_deployment_post(self):
        """Test case for v1_callhome_deployment_post

        Deploy internal call home server (v1)  # noqa: E501
        """
        pass

    def test_v1_callhome_disable_delete(self):
        """Test case for v1_callhome_disable_delete

        Unregister call home servers  # noqa: E501
        """
        pass

    def test_v1_callhome_enable_post(self):
        """Test case for v1_callhome_enable_post

        Enable call home functionality  # noqa: E501
        """
        pass

    def test_v1_callhome_external_register_post(self):
        """Test case for v1_callhome_external_register_post

        Register external call home servers (v1)  # noqa: E501
        """
        pass

    def test_v1_callhome_internal_register_post(self):
        """Test case for v1_callhome_internal_register_post

        Activate and register internal call home server  # noqa: E501
        """
        pass

    def test_v1_callhome_internal_upgrade_post(self):
        """Test case for v1_callhome_internal_upgrade_post

        Upgrade internal SRS software  # noqa: E501
        """
        pass

    def test_v2_callhome_deployment_post(self):
        """Test case for v2_callhome_deployment_post

        Deploy internal call home server (v2)  # noqa: E501
        """
        pass

    def test_v2_callhome_external_register_post(self):
        """Test case for v2_callhome_external_register_post

        Register external call home servers (v2)  # noqa: E501
        """
        pass

    def test_v2_callhome_info(self):
        """Test case for v2_callhome_info

        Get call home server information (v2)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
