# coding: utf-8

"""
    VxRail REST API

    The VxRail REST API provides a programmatic interface for performing VxRail administrative tasks. Data is available in JSON format.  # noqa: E501

    OpenAPI spec version: 8.0.020
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.chassis_information_api import ChassisInformationApi  # noqa: E501
from swagger_client.rest import ApiException


class TestChassisInformationApi(unittest.TestCase):
    """ChassisInformationApi unit test stubs"""

    def setUp(self):
        self.api = ChassisInformationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1_chassis_get(self):
        """Test case for v1_chassis_get

        Get a list of VxRail chassis (v1)  # noqa: E501
        """
        pass

    def test_v1_chassis_id_get(self):
        """Test case for v1_chassis_id_get

        Get information about a user-specified chassis (v1)  # noqa: E501
        """
        pass

    def test_v2_chassis_get(self):
        """Test case for v2_chassis_get

        Get a list of VxRail chassis (v2)  # noqa: E501
        """
        pass

    def test_v2_chassis_id_get(self):
        """Test case for v2_chassis_id_get

        Get information about a user-specified chassis (v2)  # noqa: E501
        """
        pass

    def test_v3_chassis_get(self):
        """Test case for v3_chassis_get

        Get a list of VxRail chassis (v3)  # noqa: E501
        """
        pass

    def test_v3_chassis_id_get(self):
        """Test case for v3_chassis_id_get

        Get information about a user-specified chassis (v3)  # noqa: E501
        """
        pass

    def test_v4_chassis_get(self):
        """Test case for v4_chassis_get

        Get a list of VxRail chassis (v4)  # noqa: E501
        """
        pass

    def test_v4_chassis_id_get(self):
        """Test case for v4_chassis_id_get

        Get information about a user-specified chassis (v4)  # noqa: E501
        """
        pass

    def test_v5_chassis_get(self):
        """Test case for v5_chassis_get

        Get a list of VxRail chassis (v5)  # noqa: E501
        """
        pass

    def test_v5_chassis_id_get(self):
        """Test case for v5_chassis_id_get

        Retrieves information about a user-specified chassis (v5)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
