# coding: utf-8

"""
    VxRail REST API

    The VxRail REST API provides a programmatic interface for performing VxRail administrative tasks. Data is available in JSON format.  # noqa: E501

    OpenAPI spec version: 8.0.020
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.host_removal_api import HostRemovalApi  # noqa: E501
from swagger_client.rest import ApiException


class TestHostRemovalApi(unittest.TestCase):
    """HostRemovalApi unit test stubs"""

    def setUp(self):
        self.api = HostRemovalApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1_cluster_remove_host_post(self):
        """Test case for v1_cluster_remove_host_post

        Remove a host from the cluster  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
