# coding: utf-8

"""
    VxRail REST API

    The VxRail REST API provides a programmatic interface for performing VxRail administrative tasks. Data is available in JSON format.  # noqa: E501

    OpenAPI spec version: 8.0.020
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.idrac_network_ipv6_spec_ipv4 import IdracNetworkIPv6SpecIpv4  # noqa: E501
from swagger_client.rest import ApiException


class TestIdracNetworkIPv6SpecIpv4(unittest.TestCase):
    """IdracNetworkIPv6SpecIpv4 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIdracNetworkIPv6SpecIpv4(self):
        """Test IdracNetworkIPv6SpecIpv4"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.idrac_network_ipv6_spec_ipv4.IdracNetworkIPv6SpecIpv4()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
