# coding: utf-8

"""
    VxRail REST API

    The VxRail REST API provides a programmatic interface for performing VxRail administrative tasks. Data is available in JSON format.  # noqa: E501

    OpenAPI spec version: 8.0.020
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.system_init_spec_v5_vxrail_managed_witness_node_witness_vm import SystemInitSpecV5VxrailManagedWitnessNodeWitnessVm  # noqa: E501
from swagger_client.rest import ApiException


class TestSystemInitSpecV5VxrailManagedWitnessNodeWitnessVm(unittest.TestCase):
    """SystemInitSpecV5VxrailManagedWitnessNodeWitnessVm unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSystemInitSpecV5VxrailManagedWitnessNodeWitnessVm(self):
        """Test SystemInitSpecV5VxrailManagedWitnessNodeWitnessVm"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.system_init_spec_v5_vxrail_managed_witness_node_witness_vm.SystemInitSpecV5VxrailManagedWitnessNodeWitnessVm()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
