# coding: utf-8

"""
    VxRail REST API

    The VxRail REST API provides a programmatic interface for performing VxRail administrative tasks. Data is available in JSON format.  # noqa: E501

    OpenAPI spec version: 8.0.020
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.bandwidth_throttling_information_api import BandwidthThrottlingInformationApi  # noqa: E501
from swagger_client.rest import ApiException


class TestBandwidthThrottlingInformationApi(unittest.TestCase):
    """BandwidthThrottlingInformationApi unit test stubs"""

    def setUp(self):
        self.api = BandwidthThrottlingInformationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_v1_system_bandwidth_throttling(self):
        """Test case for get_v1_system_bandwidth_throttling

        Get bandwidth throttling information  # noqa: E501
        """
        pass

    def test_put_v1_system_bandwidth_throttling(self):
        """Test case for put_v1_system_bandwidth_throttling

        Update bandwidth throttling information  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
