# coding: utf-8

"""
    VxRail REST API

    The VxRail REST API provides a programmatic interface for performing VxRail administrative tasks. Data is available in JSON format.  # noqa: E501

    OpenAPI spec version: 8.0.020
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.system_init_spec_v5_network1_vds import SystemInitSpecV5Network1Vds  # noqa: E501
from swagger_client.rest import ApiException


class TestSystemInitSpecV5Network1Vds(unittest.TestCase):
    """SystemInitSpecV5Network1Vds unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSystemInitSpecV5Network1Vds(self):
        """Test SystemInitSpecV5Network1Vds"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.system_init_spec_v5_network1_vds.SystemInitSpecV5Network1Vds()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
