# coding: utf-8

"""
    VxRail REST API

    The VxRail REST API provides a programmatic interface for performing VxRail administrative tasks. Data is available in JSON format.  # noqa: E501

    OpenAPI spec version: 8.0.020
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.layer3_segment_start_spec import Layer3SegmentStartSpec  # noqa: E501
from swagger_client.rest import ApiException


class TestLayer3SegmentStartSpec(unittest.TestCase):
    """Layer3SegmentStartSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLayer3SegmentStartSpec(self):
        """Test Layer3SegmentStartSpec"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.layer3_segment_start_spec.Layer3SegmentStartSpec()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
