# coding: utf-8

"""
    VxRail REST API

    The VxRail REST API provides a programmatic interface for performing VxRail administrative tasks. Data is available in JSON format.  # noqa: E501

    OpenAPI spec version: 8.0.020
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.telemetry_reporting_api import TelemetryReportingApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTelemetryReportingApi(unittest.TestCase):
    """TelemetryReportingApi unit test stubs"""

    def setUp(self):
        self.api = TelemetryReportingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1_post_telemetry_tier_setting_information(self):
        """Test case for v1_post_telemetry_tier_setting_information

        Set the telemetry tier  # noqa: E501
        """
        pass

    def test_v1_query_telemetry_tier_setting_information(self):
        """Test case for v1_query_telemetry_tier_setting_information

        Get the telemetry tier  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
