# coding: utf-8

"""
    VxRail REST API

    The VxRail REST API provides a programmatic interface for performing VxRail administrative tasks. Data is available in JSON format.  # noqa: E501

    OpenAPI spec version: 8.0.020
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.system_credentials_api import SystemCredentialsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSystemCredentialsApi(unittest.TestCase):
    """SystemCredentialsApi unit test stubs"""

    def setUp(self):
        self.api = SystemCredentialsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1_system_update_credential_post(self):
        """Test case for v1_system_update_credential_post

        Update the management user passwords (v1)  # noqa: E501
        """
        pass

    def test_v1_system_validate_credential_post(self):
        """Test case for v1_system_validate_credential_post

        Validate the supplied user credentials  # noqa: E501
        """
        pass

    def test_v2_system_update_credential_post(self):
        """Test case for v2_system_update_credential_post

        Update the management user passwords (v2)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
