# coding: utf-8

"""
    VxRail REST API

    The VxRail REST API provides a programmatic interface for performing VxRail administrative tasks. Data is available in JSON format.  # noqa: E501

    OpenAPI spec version: 8.0.020
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.vx_rail_installation_api import VxRailInstallationApi  # noqa: E501
from swagger_client.rest import ApiException


class TestVxRailInstallationApi(unittest.TestCase):
    """VxRailInstallationApi unit test stubs"""

    def setUp(self):
        self.api = VxRailInstallationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1_system_initialize_customer_supplied_hosts_post(self):
        """Test case for v1_system_initialize_customer_supplied_hosts_post

        Return nodes by customer supplied management IP  # noqa: E501
        """
        pass

    def test_v1_system_initialize_disk_slot_mappings_get(self):
        """Test case for v1_system_initialize_disk_slot_mappings_get

        Get disk slot mappings for hosts  # noqa: E501
        """
        pass

    def test_v1_system_initialize_nodes_get(self):
        """Test case for v1_system_initialize_nodes_get

        Return nodes by auto discovery  # noqa: E501
        """
        pass

    def test_v1_system_initialize_post(self):
        """Test case for v1_system_initialize_post

        Configure and deploy a new VxRail cluster  # noqa: E501
        """
        pass

    def test_v1_system_initialize_status_get(self):
        """Test case for v1_system_initialize_status_get

        Get VxRail cluster configuration and deployment status  # noqa: E501
        """
        pass

    def test_v2_system_initialize_customer_supplied_hosts_post(self):
        """Test case for v2_system_initialize_customer_supplied_hosts_post

        Return nodes by customer supplied management IP  # noqa: E501
        """
        pass

    def test_v2_system_initialize_nodes_get(self):
        """Test case for v2_system_initialize_nodes_get

        Return nodes by auto discovery  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
